version: 2.1

jobs:
  build-and-test:
    # working_directory: ~/
    docker:
      - image: circleci/python:3.7.5
    steps:
      - checkout
      - restore_cache:
          keys:
            - pip -- {{ checksum "requirements.txt"}}
      - run:
          name: Install dependencies
          command: pip install --user -r requirements.txt
      - save_cache:
          key: pip -- {{ checksum "requirements.txt"}}
          paths: /home/circleci/.local/bin/
      - run:
          command: python manage.py test
          name: Test
  deploy:
    machine:
      image: circleci/python:3.7.5
    steps:
      - checkout
      - add_ssh_keys:
      - run: ssh ${USER_NAME}@${HOST_NAME} 'cd my-django && git pull origin main && sudo systemctl restart gunicorn.socket'

workflows:
  main:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
          filters:
            breanches:
              only: main