# Generated by Django 2.2.7 on 2020-08-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
                ('classification', models.CharField(max_length=255, null=True, verbose_name='分類')),
                ('text', models.CharField(max_length=255, null=True, verbose_name='内容')),
                ('updateTime', models.DateTimeField(verbose_name='更新日時')),
            ],
            options={
                'db_table': 'ARTICLE',
            },
        ),
        migrations.DeleteModel(
            name='DocumentationModel',
        ),
    ]
