# Generated by Django 2.2.7 on 2020-08-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200802_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='classification',
            field=models.IntegerField(choices=[(1, 'documentation'), (2, 'errorlog'), (3, 'diary')], verbose_name='分類'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='text',
            field=models.TextField(null=True, verbose_name='内容'),
        ),
    ]
