# Generated by Django 2.2.7 on 2020-08-02 07:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200802_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='updateTime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日時'),
        ),
    ]
