# Generated by Django 2.2.7 on 2020-08-07 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_article_category_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleModel',
        ),
    ]
